
#let iffd = $arrow.double.b.t$
#let uu = $union$
#let uud = $union.dot$
#let nn = $sect$
#let bs = $backslash$
#let ub = $union.big$
#let sb = $sect.big$
#let symd = $triangle.t.stroked$
#let iff = $<=>$
#let tb(exp, top, bottom) = $attach(limits(#exp), b: #bottom, t: #top)$
#let bv(f, s) = $#f bar.v_#s$
#let id(s) = $"id"_#s$
#let Im(f) = $"Im"(#f)$
#let dom(f) = $"dom"(#f)$
#let seq = $subset.eq$
#let suq = $supset.eq$
#let xx = $times$
#let A1 = $A_1$
#let A2 = $A_2$
#let B1 = $B_1$
#let B2 = $B_2$
#let RNN = $RR^+_0$
#let QED = align(end, $qed$)
#let bar(x) = $overline(#x)$
#let of = $compose$
#let pm = $plus.minus$
#let char(f) = $"char"(#f)$
#let liminf(x) = $limits(lim #x)_(n->oo)$
#let limitn = $limits(lim)_(n->oo)$
#let arrl = $arrow.l.double$
#let an = $a_n$
